version: '3.8'

x-common_env: &common_env
  PORT: ${PORT}
  DATABASE_USER: ${DATABASE_USER}
  DATABASE_PASS: ${DATABASE_PASS}

services:
  db:
    container_name: database
    image: postgis/postgis:14-3.3
    restart: always
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASS}
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    depends_on:
      - db
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    expose:
      - '3000'
      - '9229'
    ports:
      - '3000:3000'
      - '9229:9229'
    links:
      - db
    environment:
      NODE_ENV: development
    command: npm run dev

volumes:
  db:
    driver: local